### ISSUE TITLE
Add blurring

### ISSUE THREAD

**Issue by kammerje** [kammerje/spaceKLIP_new#6]
The functionality to blur frames by a certain factor (or to the Nyquist limit) needs to be implemented in `imagetools.py`.

**Comment by AarynnCarter** [comment]
Blurring in the first interation of spaceKLIP was applied through a defined sigma value that was eventually passed to a gaussian_filter() command. Like @kammerje mentions above, it would be nice if this value could be calculated directly from the wavelength of the filter and the pixel scale.

**Comment by kammerje** [comment]
Implemented with [this](https://github.com/kammerje/spaceKLIP_new/commit/dd483da50fa4b6f017bad5851a02c6521b7ef0e2) commit, closing issue.
